In [31]:
import pandas as pd  
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [32]:
df = pd.read_csv('train.csv')

In [33]:
df

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0
...,...,...,...,...,...,...
404285,404285,433578,379845,How many keywords are there in the Racket prog...,How many keywords are there in PERL Programmin...,0
404286,404286,18840,155606,Do you believe there is life after death?,Is it true that there is life after death?,1
404287,404287,537928,537929,What is one coin?,What's this coin?,0
404288,404288,537930,537931,What is the approx annual cost of living while...,I am having little hairfall problem but I want...,0
404289,404289,537932,537933,What is like to have sex with cousin?,What is it like to have sex with your cousin?,0

In [34]:
df.isnull().sum()

id              0
qid1            0
qid2            0
question1       1
question2       2
is_duplicate    0
dtype: int64

In [35]:
df.dropna(inplace=True)

In [36]:
df

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0
...,...,...,...,...,...,...
404285,404285,433578,379845,How many keywords are there in the Racket prog...,How many keywords are there in PERL Programmin...,0
404286,404286,18840,155606,Do you believe there is life after death?,Is it true that there is life after death?,1
404287,404287,537928,537929,What is one coin?,What's this coin?,0
404288,404288,537930,537931,What is the approx annual cost of living while...,I am having little hairfall problem but I want...,0
404289,404289,537932,537933,What is like to have sex with cousin?,What is it like to have sex with your cousin?,0

In [37]:
df.duplicated().sum()

np.int64(0)

In [38]:
df['is_duplicate'].value_counts()
# slight imbalance

is_duplicate
0    255024
1    149263
Name: count, dtype: int64

In [39]:
new_df = df.sample(30000)

In [40]:
new_df.isna().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [41]:
new_df

,id,qid1,qid2,question1,question2,is_duplicate
11908,11908,22977,22978,What kind of fruits do you eat?,What kind of fruit do you eat?,1
83352,83352,141132,141133,What is Google Hangouts on Air?,What are Google Hangouts On Air?,1
383696,383696,120860,41470,What are few best exercise to lose weight?,What are the best home exercises to lose weight?,1
186846,186846,284909,35804,How do I add photos to Quora?,How do I add photos on Quora?,1
109766,109766,180099,180100,How much money do you earn after 5 years and a...,Where do people who get a 1 crore package afte...,0
...,...,...,...,...,...,...
143544,143544,6438,30681,How can I make money online for job?,How can I make money online quickly and easily?,1
362508,362508,492409,492410,Are applications that allow me to download son...,"How is the ""free music download"" app legal?",0
179469,179469,275378,275379,What are the basics I need to learn as an elec...,What are the main reasons why students from Ku...,0
100798,100798,167118,167119,Would a one-party system be better for the Uni...,Is it worth supporting an emerging third party...,0
64114,64114,111466,111467,If the total cost of three books and four pens...,The total cost of three books and four pens is...,1

In [42]:
ques_df = new_df[['question1' , 'question2']]

In [43]:
ques_df

,question1,question2
11908,What kind of fruits do you eat?,What kind of fruit do you eat?
83352,What is Google Hangouts on Air?,What are Google Hangouts On Air?
383696,What are few best exercise to lose weight?,What are the best home exercises to lose weight?
186846,How do I add photos to Quora?,How do I add photos on Quora?
109766,How much money do you earn after 5 years and a...,Where do people who get a 1 crore package afte...
...,...,...
143544,How can I make money online for job?,How can I make money online quickly and easily?
362508,Are applications that allow me to download son...,"How is the ""free music download"" app legal?"
179469,What are the basics I need to learn as an elec...,What are the main reasons why students from Ku...
100798,Would a one-party system be better for the Uni...,Is it worth supporting an emerging third party...
64114,If the total cost of three books and four pens...,The total cost of three books and four pens is...

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

In [45]:
questions = list(ques_df['question1']) + list(ques_df['question2'])

In [46]:
questions

['What kind of fruits do you eat?',
 'What is Google Hangouts on Air?',
 'What are few best exercise to lose weight?',
 'How do I add photos to Quora?',
 'How much money do you earn after 5 years and after 10 years, after getting a starting salary package of around 7 lac/year after graduation?',
 'How can you be a restorer?',
 'Why are some people disrespectful?',
 'Is a central university like Babasaheb Bhimrao Ambedkar University in Lucknow better than the top private universities like SRM and BITS for B.Tech.?',
 'Which are the biggest airport runways in the world?',
 'Why would bad things ever happen to good people?',
 'How do you start writing poetry?',
 'How do I find a lost mobile in India?',
 'What is a secret which you would not tell anybody in real life, but would on Quora using anonymity?',
 'What if Bernie Sanders had won the Democratic nomination, would he have been chosen as president?',
 'Is ZzzQuil generic?',
 'What is the best part of being a mother?',
 'While reading in public or giving speech from a text, how should you read the content in between the parentheses? Should you not read it?',
 'How long does fat grafting last?',
 'If I should start a vinyl wrapping business for leased cars on the side for $1100 would people support it?',
 'What is the best way to mend a broken heart?',
 'Which CNG kit shall I fit to my maruti sx4, lovato or tomesetto?',
 'I really like this girl. She lives pretty far away. Is long distance relationship a good idea?',
 'Who is the best guitarist?',
 'How can human teleportation be achieved?',
 'What is the best cookie recipe?',
 'Do you think the UK Parliament should vote about invoking article 50?',
 'Are prostitutes and porn stars forced to do those things are do they choose to?',
 'What are the most interesting products and innovations that Real Industry is coming out with in 2016?',
 'Which is the best mysterious scary photo ever?',
 'How can one start an internet broadband service provider company in India?',
 'Is it possible to do MS in Germany after dual degree?',
 'Are there other countries that use an electoral college aside from the U.S.?',
 "Can a person's Animagus form be a Werewolf?",
 'What is structural design?',
 'Why is tea naturally caffeinated?',
 'What are the characteristics of a person with an INFP personality?',
 'Tattoos: What is the meaning behind an eight-ball design?',
 'How do I apologise to my mother?',
 'What does "put your ass in the sink" mean?',
 'What are the reasons why Catholic priests wear the white collar?',
 "How will YouTube's popularity change over the next five years?",
 'If Ted Cruz weaseled out of really denying having affairs with 5 women, how did he do it?',
 'Why do Chinese people eat rice with chopsticks, when eating with a spoon is easier?',
 'How can a blind person be great at coding?',
 'How is school changing in the 21st century in Kenya?',
 'How is the chemical formula for titin determined, and how does it compare to that of hemoglobin?',
 'What is my undertone?',
 'Where does Barron Trump go to school?',
 'How do I cure my food allergy?',
 'Why do we get Nightmares?',
 'What are the effects of Moon in 7th house in Scorpio in Taurus ascendant aspected by exalted Jupiter from 3rd house?',
 'What is your review of We Are Your Friends (2015 movie)?',
 "How do I mirror my Android's screen to my TV without a HDMI cable?",
 'How did Jeremy Clarkson of TV\'s "Top Gear" walk through Chernobyl without becoming contaminated?',
 'How can I improve my spoken English?',
 'What are the secrets only the wealthy know and the middle class is unaware of?',
 'Will Trump win the election?',
 'How much does a stock broker get from the sub broker?',
 'What are the differences between touch.Facebook.com and m.Facebook.com?',
 'What does a vagina look like?',
 'Is there a way to sync music to iPhone without iTunes?',
 "How to lock apps in Lenovo's k4 note by fingerprint?",
 'Why do I have dreams every night?',
 'Who is the hottest Bollywood actress in a bikini?',
 'What did you do before a day before JEE advanced?',
 'How does banana bread differ from banana cake?',
 "What's a common mistake students make during university?",
 'What are the various tips while learning to play the piano?',
 'What would a time machine look like?',
 'How can I get interested in football?',
 "Will Donald Trump's supporters be disappointed if he doesn't deliver his top campaign promises like the wall, deportation and Muslim ban?",
 'Who wrote the koran?',
 'How should I prepare for the IAS PRELIMS in 8 months?',
 'During musical concerts (orchestra), we always see a person (musician) standing in the front (with his back to the crowd) waving a wand/stick in one hand and seemingly guiding the musicians. Does he actually have any role or is just like a leader for representation purposes?',
 'Why do we have lawyers?',
 'How is life as a technical support engineer at IBM?',
 'Has Uber or similar app dominates the online cab market in your country?',
 "What was Sundar Pachai's MBA major/specialization?",
 'Why should I vote for Hillary Clinton?',
 'Why my question was marked as needing imrovement?',
 'How do you focus on God?',
 'How do l study efficiently?',
 'How can this complicated universe have no creator?',
 'What are the most popular job websites in Slovakia?',
 'How can I check the status of my pan card?',
 'What is your take on prohibition of 1000 and 500 rupees note? Is it going to boost our economy and give us the country we wish for?',
 'What would cause my period to come 8 days early?',
 'What is the process of powder coating process with powder coating line?',
 'What is the point of Video Marketing?',
 'Why do Tamilians learn Hindi, but not Marathi, Bengali, or Gujarati when they go to Mumbai, Pune or Kolkata and Gujarat?',
 'Can I get pregnant two days after my period ends?',
 'Why does Quora mark my questions as needing improvement/clarification before I have time to give it details? Literally within seconds…',
 'What are some of the best video games of 2015?',
 'What is the best way to start learning about virtual reality game development and technical knowledge about VR?',
 'What was the best day of your life? What happened?',
 'Is Christianity incompatible with science?',
 'What is metabolic shock? What are its symptoms?',
 'What are some good was to earn money online?',
 'How did dodgeball start?',
 'Why do some ants produce web (like spiders)? Is this some form evolution or mutation?',
 'Which is best online shopping site in india for bags?',
 'How does sccm work? I am trying to understand how SCCM copies app installallation files from server to a node.',
 'Is it true that the number of seats in AIIMS new Delhi will increase from 72 to 100 from 2017?',
 'How progressive is Hillary Clinton?',
 'What is your first ever anonymous question you asked on Quora?',
 'Why is World War 2 called "World" War 2 if it didn\'t affect the whole world?',
 'Is e-commerce model sustainable?',
 'When are the most promising predictions of the next recession?',
 'What does this saying mean; "Don\'t trust everything you see even salt looks like sugar"?',
 'What is the electron configuration of electron?',
 'How do I turn off caps lock on my Mac?',
 'Does Quora form intellectual bubbles?',
 'What are the puzzles asked in interview?',
 'What are the tips for long and healthy hair?',
 'What is chyawanprash?',
 'Are there any simple explanations of what IS time?',
 'Why did Tata Sons removed/sacked Cyrus Mistry as the chairman?',
 'What is the difference between ethics and moral values?',
 'What is saturation & active region in a transistor?',
 'What can I do to save my laptop battery while downloading?',
 'What is meant by stress relaxation of a material?',
 'How can I trace the location of an IP address?',
 'How do I cure myopia naturally?',
 'How can I get an internship?',
 'What are your favorite event planning apps?',
 'How are seat belts made?',
 'How do I reduce double chin?',
 'What are the best ways to speak English fluently?',
 'Is it really that difficult to be rich? Why?',
 'What kind of life do commercial pilots have?',
 'What makes Othello a tragic hero?',
 'How do I ask longer questions on Quora?',
 'How can one find his/her life purpose?',
 'Would you rather be a dragon or own a dragon?',
 'Which community colleges in the Bay Area offer courses in robotics?',
 'Is weed good or bad for you?',
 'How much sleep does one require?',
 'Konark temple is made up of which rock?',
 'Do you like pani puri?',
 'How can I tell if an email address is a spoofed address?',
 'How did consciousness evolve?',
 'What is the difference between a Range Rover and a Land Rover?',
 'What should Vegas tourists not do?',
 "Why does Christine Chong have 28 followers, 91 following if she hasn't asked or answered any questions? Nor made any posts,",
 'How many neutrons are in iodine?',
 'What makes a subject feel boring to you in school or education?',
 'How do I get rid of termites?',
 'The best of 2016: Which were the worst Bollywood movies in 2016?',
 'What is external respiration and how does it differ from internal respiration?',
 'What is best way for earning money?',
 'How do I convert a hexadecimal number to BCD?',
 'What are some insane facts about Area 51?',
 'Which revolution has been the most successful: American, Russian, Chinese, Cuban, or one of the multiple French?',
 'What is your typical day like?',
 'What is Godrej Emerald thane?',
 'Why do so many people ask questions on Quora that can be found in a Google search?',
 'What is the most illegal thing you have done with your computer?',
 'Can I change my thinking?',
 'How do you become a game ui/ux designer?',
 'Is NIIT Delhi good for a digital marketing course?',
 'Why are Chinese people always apologising for their poor English?',
 'How we start preparation for IAS?',
 'Why do you, as a theist, believe a God with nothing to gain and no room for improvement changed His already perfect existence by creating?',
 'Why doesn’t the Chinese president Xi attend the funeral of Shimon Peres and Mandela?',
 'What do b/f c/f b/d c/d mean in financial accounting?',
 "What's the worst thing you ever done in your life?",
 'What are the online money saving shopping hacks?',
 'How do I let WhatsApp store data directly to a micro SD card?',
 'What is for lunch?',
 'What are some examples of modern day unspeakable truths? I am aware of the dilemma in my question. I am curious. Please no political rants.',
 'Evaluate the assertion that interviews in qualitative research are characterised by struggle between interviewer and interviewee?',
 'Is kabbalah philosophy?',
 'Do eating out on dates increase your weight?',
 'What is a retailers’ cooperative?',
 'Why is European wildlife so dull compared to the rest of the world?',
 'What is your worst breakup experience?',
 'What are the pros and cons to being a cosmetologist?',
 'What was the significance of the battle of Somme, and how did this battle compare and contrast to the Battle of Nanshan?',
 'Where can I find the latest version.of kmspico to activate windows 10?',
 'What is the best programming/coding language to learn?',
 'Why do so many people support Donald Trump?',
 'Is it true that most colleges fill their early decision pool primarily with people with legacy and recruited athletes?',
 'How can you deal with a cat that is scared of everything?',
 'Career after MS from USA?',
 'Why is Raghuram Rajan popular?',
 'What is the difference between evaporation and melting?',
 'Why do so many people buy the Royal Enfield Thunderbird 350 cc when the 500 cc is better?',
 'Does adroid staff use iPhone?',
 'What are the best fairness creams for men in India?',
 'What are some extremely early signs of pregnancy?',
 'Why are cells different sizes and shapes?',
 'Is it healthy to lose 20 pounds in 2 months?',
 'What is the difference between computer science and electrical and computer engineering?',
 'If one were to travel on a skateboard, would they use more or less energy than walking?',
 'What are arguments in favor of Israeli settlements?',
 'What does kamaria mean in Urdu?',
 'What do game developers do?',
 "Why is Lipton's green tea helpful for losing weight?",
 'It is safe to take co-codamol while being pregnant?',
 'How does stock market works?',
 'Why is Rahul Gandhi?',
 'Do we need advertisements? Describe your favourite advertisement / commercial. Why is it appealing?',
 'What is the best way to prepare for job interviews?',
 'I am a CSE student and I wanna buy a laptop for 4 years under 60k?',
 'What is the history of public administration?',
 'Can I play a high graphic game on my TV connected through laptop with an HDMI cable?',
 'Why do I experience chest pain while I playing football (Soccer)?',
 'How do I learn Design pattern in jQuery?',
 'What does the death of some other person in your dream signifies?',
 "With all the things we are sending into space, don't we run the risk of making the earth smaller?",
 'What is the story behind Stoning of the Devil in Hajj?',
 'How do virtual machines use RAM?',
 'Do you think we are on the verge of World War III?',
 'What are some ways to whiten your teeth using lemon?',
 "How can the drive from Edmonton to Auckland be described, and how do these cities' attractions compare to those in Victoria?",
 'What is the best coaching for medical entrance in Nagpur?',
 'Can I buy a car in Texas with drivers licence restriction B?',
 'How Natalie Portman helps empower women’s in Kenya People?',
 'Why do orcs in The Hobbit look different than in The Lord of the Rings?',
 'What is golden age?',
 'Which are the best digital marketing firms in Banglore?',
 'I am expecting 240 marks in the JEE Mains paper, 2 B.Arch. and 59% in 12th boards. What is the best college that I can get for architecture?',
 'How do I get admission in IIT?',
 'Why should one join the Indian Foreign Service?',
 'What are the best way of loose the weight?',
 'What is best of a MUN?',
 'What should one know about the Indian education system?',
 'How can you find the purpose of human life?',
 'How much money do you earn by posting a video on YouTube?',
 'What happens if I report an account on Instagram will that person find out it was me?',
 'How will Indian GDP be affected from banning 500 and 1000 rupees notes?',
 "Why can't India get more medals in every Olympics?",
 'What is the strangest thing that happened to you as a foreigner in China?',
 'What were the consequences of WW2?',
 'When is One piece episode 517 going to be dubbed?',
 'What does nationalism mean?',
 'What should I learn after learning HTML, CSS and Bootstrap to become a freelance Web Designer?',
 'Is IELTS or pte easier?',
 'How much does an executive in the Tech industry value management consulting experience in a potential recruit?',
 'What is the difference between piston and plunger pumps?',
 'What is the difference between iTunes and Apple Music?',
 'Which companies provide two-way, send and receive, SMS API for India?',
 'What are the legal implications, if any, for a lady retaining her maiden surname post-marriage in India?',
 'What annoys you about Quora?',
 'Is flax is used for making ropes and gunny bags?',
 'How are mail order brides marketed?',
 'How do you become a dentist?',
 'How do I learn to observe people like Sherlock Holmes?',
 'What are the best books on diplomacy?',
 'Why do Russians use ")" as a smiley instead of ":)"?',
 'What are some popular method to do suicide?',
 "What's a full form of computer?",
 "My straight best friend know that I'am gay, and he stay away from me, what shoud I do?",
 'Doing job just after graduation is a good option?',
 'When was Jesus born?',
 'How do I unlock BitLocker without recovery key and password?',
 'Why is WikiLeaks helping Donald Trump?',
 'How can I earn money online?',
 'How do you find your list of recently watched videos on Amazon Prime Instant Video?',
 'Why do we need to purchase platform ticket in Indian railway stations?',
 'What I can do to save our environment?',
 'What is the difference between Facebook and Twitter?',
 'How do I get rid of wrinkles around my eyes?',
 "I was suddenly logged off Gmail. I can't remember my Gmail password and just realized the recovery email is no longer alive. What can I do?",
 'What are some entry-level to average-level jobs predominantly involving reading?',
 'How much time does it take to update Aadhaar details online?',
 'What are the best gaming laptops under ₹65000?',
 'What is better to learn first python2x or Python 3x?',
 'What universities does Mohawk Industries recruit new grads from? What majors are they looking for?',
 'How do I get 85%+ in CBSE with only 3 months left for board examinations?',
 'What is the best place to get a haircut in Kolkata?',
 'Which one is better, Stock ROM or Custom ROM?',
 'What happens at the end of the 2002 movie Chance?',
 'Why was the jury system abolished in India?',
 'What are some movies that everyone needs to watch at least once in life?',
 'How do you calculate your net worth?',
 'What are the major advantages and differences between single rear wheel and dual rear wheel pickup trucks?',
 'How do I relate the skin colour with the genotype?',
 'What are the best movies every youngster must watch?',
 'Is it true that Google is stealing our data and personal information?',
 "What are good gifts for a foreign visitor to bring when they're invited to someone's home in Bhutan for the first time?",
 'What is real Italian Leather? How can you tell its difference from other types of leather?',
 'Is it okay for a 12 year old to date a 13 year old?',
 'What are the effects of long term sleep deprivation?',
 'How are Korean names translated to Japanese?',
 'What is Q Continuum?',
 "Why isn't Seinfeld on iTunes?",
 'Why did my ex block me on her Facebook?',
 'What is Chhath Puja? How it is celebrated?',
 'What is the best free online IQ test?',
 'What is the property tax rate in Granville, Ohio? How is it compared to the one of Michigan?',
 'What are good appliances for finite state machines?',
 'Why does the IP layer need to check its packages, when the Link level has already done that before?',
 'What is the business model of Shuttl App?',
 'Will India end up having a Muslim majority in the future? What will be the social, economical and political consequences if that happens?',
 'What are your views on ban of 500 and 1000 rupee notes in India?',
 'How close are we to world war?',
 'How does this speaker work?',
 'What hotel in Manali Hill-station would be safe for unmarried couples, without the harassment of police, hotel staff, and moral police?',
 'What makes a great villain?',
 'What does A2A mean and why is it being used at the bottom of some answers on Quora?',
 'How much do prostitutes charge in the Red Light District of Amsterdam?',
 'What are the NCERT books to be read for UPSC?',
 'What is the annual earning of an IAS officer?',
 'Which coaching class is good for MPSC preparation in Pune?',
 'Is listening to music a waste of time?',
 'Is a concussion only diagnosed when symptoms occur at the time of the injury?',
 'Which are best apps for photo edit?',
 'Why do designers prefer to use Mac than PC?',
 'How do the gyroscopes in smart phones work?',
 'How do I avoid illness of the child?',
 'What are some examples of positive and negative feedback?',
 'How many Facebook victims were there in 2010?',
 'Are there any characteristics that the Japanese economy has that do not align with the characteristics of the CME model in the VoC approach?',
 'What are the best techniques for off-page SEO?',
 'I am very much confused. Did man really land on moon? Please answer honestly with proof.',
 'You have 1000 wine bottles, one of which is poisoned. You want to determine which bottle is poisoned by feeding the wines to the rats. The poisoned wine takes one hour to work. How many rats are necessary to find the poisoned bottle in one hour?',
 'How can I lose weight effectively?',

In [47]:
cv = CountVectorizer(max_features=3000)
# 3000 most frequent used words will be used as a vocabulary

In [48]:
q1_arr , q2_arr = np.vsplit(cv.fit_transform(questions).toarray() , 2)
# text representation of all our questions

In [51]:
temp_df1 = pd.DataFrame(q1_arr , index=ques_df.index)
temp_df2 = pd.DataFrame(q2_arr , index=ques_df.index)

In [52]:
temp_df = pd.concat([temp_df1 , temp_df2] , axis=1)

In [53]:
temp_df.shape

(30000, 6000)

In [55]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
11908,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
83352,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
383696,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
186846,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109766,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143544,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
362508,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
179469,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100798,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [56]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [57]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
11908,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
83352,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
383696,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
186846,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
109766,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143544,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
362508,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
179469,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100798,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [63]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(temp_df.iloc[: , 0:-1].values , temp_df.iloc[: , -1].values , test_size = 0.2 , random_state = 48)

In [64]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [65]:
rf.fit(x_train , y_train)

RandomForestClassifier()

In [66]:
y_pred = rf.predict(x_test)

In [67]:
from sklearn.metrics import accuracy_score

In [68]:
accuracy_score(y_test , y_pred)

0.7406666666666667

In [ ]:
# THIS IS BASIC SIMPLE APPROACH

In [ ]:
# we will add 7 new features to this